language: go

go:
  - tip

if: tag IS present

before_install:
  - go get -t -v ./...
script:
  - curl -sfL https://git.io/goreleaser | sh -s -- check

deploy:
- provider: script
  cleanup: false
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux